### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tirzah2** [elpossum/fvtt-combat-range-overlay#7]
Hi!
Is there any way to use measurable templates as difficult terrains? The enhanced terrain module I don't think works for the newest versions if foundry.

**Comment by GhostwheelX** [comment]
Perhaps somehow add compatibility to the [Terrain Mapper](https://github.com/caewok/fvtt-terrain-mapper) module?

**Comment by elpossum** [comment]
Enhanced Terrain Layer does work to some degree: the template side of the module is still functional and works with this module. [The ETL v11 support issue might be of some help to see how to use it.](https://github.com/ironmonk88/enhanced-terrain-layer/issues/142#issuecomment-1685372418). I'm working on [Terrain Mapper](https://github.com/caewok/fvtt-terrain-mapper) integration.
