### ISSUE TITLE
Bug with color of grid

### ISSUE THREAD

**Issue by roi007leaf** [elpossum/fvtt-combat-range-overlay#9]
getting no color to the grid at all
![image](https://github.com/elpossum/fvtt-combat-range-overlay/assets/17231451/3464ab14-1b3c-444a-a587-4a5490036603)

**Comment by roi007leaf** [comment]
grid also doesnt gets erased on turn change

**Comment by elpossum** [comment]
I've just tested using that and it seemed fine. It could be interacting with another module that I'm not using though I can't think how. Could you tell me what you do to get the error?

For the turn change, do you want it to only show the overlay if the controlled token is the active combatant?

**Comment by roi007leaf** [comment]
Yes  it should only show the overlay for the controlled token, to not clutter the canvas

**Comment by roi007leaf** [comment]
@elpossum i tried the new update, the bug that the grid is on top of all the other overlays is still existing, it should only render one overlay for the active combatant. also it should get deleted at combat end

**Comment by roi007leaf** [comment]
![image](https://github.co@elpossum i passed about 5-6 turns
elpossum/fvtt-combat-range-overlay/assets/17231451/2c990528-2136-496f-b52d-6153e89c6dbe)
@e

**Comment by elpossum** [comment]
I can't reproduce this but I have had a similar error before that I thought I had fixed.
Can you describe the steps you took to trigger this and the module settings? Or send me your world.

**Comment by roi007leaf** [comment]
Sure I'll send you my world gimme a min to upload to drive

**Comment by roi007leaf** [comment]
@elpossum https://drive.google.com/file/d/1Nl4Rue2c406UkNZIhh9bUNMYjl40i7S0/view?usp=sharing

**Comment by elpossum** [comment]
@roi007leaf Thanks. I am still unfortunately unable to reproduce this bug, even in your world, and am struggling to see what I'm missing. Any more detail would be appreciated.

**Comment by roi007leaf** [comment]
I can send you the list of my modules if that can help?

Best regards,
Roi Horowitz

**Comment by elpossum** [comment]
That might help: it does seem like it could be module related.

**Comment by roi007leaf** [comment]
@elpossum 
here you go:
### Active Modules
Ambient Soundbits v2.1.0
Arms Reach v2.3.6 [Bugs URL](https://github.com/p4535992/foundryvtt-arms-reach/issues)
Autocomplete Whisper v1.0.5
Baileywiki Mass Edit v1.62.3
Battlezoo Bestiary for Pathfinder 2e by Roll For Combat v2.5
Battlezoo Bestiary: Strange and Unusual for Pathfinder 2e by Roll For Combat v1.0
Battlezoo Jewel of the Indigo Isles for Pathfinder 2e by Roll for Combat v3.1.1
Battlezoo — World of Battlezoo: Indigo Isles for Pathfinder 2e v1.1.2
Better Roofs v1.9.2
Break Time v11.03 [Bugs URL](https://github.com/ironmonk88/breaktime/issues)
Carousel Combat Tracker v2.7.5
Chat Images v3.2
Cleaner sheet title bar v1.5.2
Combat Booster: Turn Marker, Recent Actions and more v3.6.3
ConversationHUD v5.3.1
Custom CSS v2.2.2 [Bugs URL](https://github.com/cswendrowski/FoundryVTT-Custom-CSS/issues)
Dice So Nice! v4.6.10 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
The Rollsmith - Dungeon Delve - Bone Yard Dice Set v1.0.0 [Bugs URL](https://therollsmith.com/contact/)
Dice Tray v2.1.9
Dig Down - Advanced Search v2.8.2
Drag Ruler v1.13.8 [Bugs URL](https://github.com/manuelVo/foundryvtt-drag-ruler/issues)
PF2e Drag Ruler Integration v3.0.9
Enhanced Terrain Layer v11.14
Terrain Ruler v1.7.6 [Bugs URL](https://github.com/manuelVo/foundryvtt-terrain-ruler/issues)
Filepicker + v3.10
Force Client Settings v2.4.1 [Bugs URL](https://gitlab.com/kimitsu_desu/force-client-settings/-/issues)
FXMaster v4.0.2 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
Gatewalkers - Basis Pack v2.1.0
Health Estimate v31.8.3 [Bugs URL](https://github.com/mclemente/healthEstimate/issues)
Hook Macros v2.1.1
Hover Distance v2.8
Item Piles v2.9.0 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
Jam and Jax NPC Index: Undead Templates v1.25
Jam and Jax's NPC Index: Monstrous Templates v1.00
Jam and Jax's NPC Index: Specialists v1.12
Jam and Jax's NPC Index: Spellcaster v1.021
Jam and Jax's NPC Index: Warriors v1.721
JB2A - Patreon Complete Collection v0.6.6
Legendary Games' Faerie Bestiary (Pathfinder Second Edition) v1.0.0
Forien's Copy Environment vv2.2.0 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/issues)
libWrapper v1.12.13.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
Settings Extender v1.2.2
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
LiveKit AVClient v0.5.25 [Bugs URL](https://github.com/bekriebel/fvtt-module-avclient-livekit/issues)
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Active Tile Triggers v11.22 [Bugs URL](https://github.com/ironmonk88/monks-active-tiles/issues)
Monk's Combat Details v11.14 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Little Details v11.08 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's Scene Navigation v11.04 [Bugs URL](https://github.com/ironmonk88/monks-scene-navigation/issues)
Monk's Sound Enhancements v11.06 [Bugs URL](https://github.com/ironmonk88/monks-sound-enhancements/issues)
Monk's TokenBar v11.15 [Bugs URL](https://github.com/ironmonk88/monks-tokenbar/issues)
Monk's Wall Enhancement v11.02 [Bugs URL](https://github.com/ironmonk88/monks-wall-enhancement/issues)
Moulinette Core v11.8.1
Moulinette Scenes (module) v11.1.5
Moulinette Sounds & SoundPad (module) v11.8.3
Multiple Document Selection v11.03 [Bugs URL](https://github.com/ironmonk88/multiple-document-selection/issues)
Ownership Viewer v11.5 [Bugs URL](https://github.com/mclemente/fvtt-module-permission-viewer/issues)
Party Resources v1.6.0
PF2e Additional Automations v0.0.3
PF2e Automations (Patreon) v0.0.2
PF2e Companion Compendia v6.1
PF2e Dailies v2.24.0 [Bugs URL](https://github.com/reonZ/pf2e-dailies/issues)
PF2e Dorako UX v1.3.5 [Bugs URL](https://github.com/Dorako/pf2e-dorako-ux/issues)
PF2E Exploration Effects vrelease-3.0.2
pf2E Extempore Effects v1.8.3 [Bugs URL](https://github.com/shemetz/pf2e-extempore-effects/issues)
PF2e Interactive Token Tooltip v1.63.0 [Bugs URL](https://github.com/reonZ/pf2e-token-hud/issues)
PF2e Item Revitalizer v1.24.0 [Bugs URL](https://github.com/robinsving/pf2e-item-revitalizer/issues)
PF2e Keybind Menagerie v5.3.2
PF2e Macro & Helper Library v0.2.8 [Bugs URL](https://github.com/esheyw/pf2e-macro-helper-library/issues)
PF2e Macros v0.0.1
PF2e Mercenary Marketplace Volume 1 v3.0.5
Pf2E Modifiers Matter v1.9.1 [Bugs URL](https://github.com/shemetz/pf2e-modifiers-matter/issues)
PF2e Party Sheet Helper v0.0.64 [Bugs URL](https://github.com/reyzor1991/pf2e-party-sheet-helper/issues)
PF2e Perception v0.39.0 [Bugs URL](https://github.com/reonZ/pf2e-perception/issues)
PF2e Ranged Combat v5.1.3 [Bugs URL](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/issues)
PF2e Reaction Checker v0.2.61 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/issues)
pF2e See Simple Scale Statistics v1.4.2 [Bugs URL](https://github.com/shemetz/pf2e-see-simple-scale-statistics/issues)
PF2e Specific Familiars v1.0.12 [Bugs URL](https://github.com/Suldrun45/pf2e-specific-familiars/issues)
PF2E Token Markers v2.3.4
PF2e Toolbelt v1.42.0 [Bugs URL](https://github.com/reonZ/pf2e-toolbelt/issues)
PF2e Use all module tokens v1.4
pf2e Utility Buttons v0.7.4
PF2e Workbench v5.58.8 [Bugs URL](https://github.com/xdy/xdy-pf2e-workbench/issues)
Pinned chat message v2.2.0
Playlist Enchantment v1.0.1
PnP - Pointer and Pings! v2.6.0 [Bugs URL](https://github.com/p4535992/foundryvtt-pointer/issues)
Polyglot v2.4.5
Power Select Toolkit v1.0
Quick Module Enable v1.3.10 [Bugs URL](https://gitlab.com/tiwato/quick_module_enable/-/issues)
Rideable v2.21.1 [Bugs URL](https://github.com/Saibot393/Rideable/issues)
routinglib v1.1.0 [Bugs URL](https://github.com/manuelVo/foundryvtt-routinglib/issues)
Sequencer v3.1.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.2.71
PF2e Animation Macros v2.17.6
Share Media v0.0.50
Simple Calendar v2.4.13 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
SmallTime v1.19.2 [Bugs URL](https://github.com/unsoluble/smalltime/issues)
SoundFx Library v1.0.2
Spotlight Omnisearch v0.8.4
Tactical Grid v1.24.1
Tile Sort v1.1
Token Elevator v1.4.4 [Bugs URL](https://gitlab.com/Weissrolf/token-elevator/-/issues)
Token Frames v1.6.3 [Bugs URL](https://github.com/yorkshirelandscape/token_frames/issues)
Tokenizer v4.2.13
Token Magic FX v0.6.5.0
PF2e Dorako UI v3.4.1 [Bugs URL](https://github.com/Dorako/pf2e-dorako-ui/issues)
Warp Gate v1.19.2
Whisper Box v3.0.2
Youtube Player Widget v0.8.1
[Uploading PackageList.json…]()

**Comment by elpossum** [comment]
Could you run [Find the Culprit](https://github.com/Moerill/fvtt-find-the-culprit)? I don't have access to all of those modules but it doesn't seem to be any of the ones I do have, though I may have missed one.

**Comment by Lendg22** [comment]
I am also having the issue of the stacking colors, I believe it may be happening because of modules which shift your controlled token abruptly, such as Monk's combat details, when initiative passes it can auto-select your next controlled token and if you already had one controlled it stacks the overlays.
I am having this issue in the latest, v12 update, for reference.

**Comment by elpossum** [comment]
That's it. Good spot. This behaviour only occurs when the visibility setting is set to `Always`, all other settings behave as expected. I'll see if I can fix.
